# Generated by Django 6.1.1 on 2026-09-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_crop_delete_cropcalendar_delete_croptype_and_more"),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name="logisticsbusiness",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="vehicle",
                    options={"managed": True},
                ),
                migrations.CreateModel(
                    name="DeliveryTrip",
                    fields=[
                        (
                            "trip_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "weight_utilization_pct",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=5, null=True
                            ),
                        ),
                        (
                            "volume_utilization_pct",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=5, null=True
                            ),
                        ),
                        ("eta", models.DateTimeField(blank=True, null=True)),
                        (
                            "current_delivery_target",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        ("trip_status", models.BigIntegerField(blank=True, null=True)),
                        (
                            "driver",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="delivery_trips",
                                to="api.user",
                            ),
                        ),
                        (
                            "vehicle",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="delivery_trips",
                                to="logistics.vehicle",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "DELIVERY_TRIPS",
                        "managed": True,
                    },
                ),
                migrations.CreateModel(
                    name="TripManifest",
                    fields=[
                        (
                            "manifest_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "dropoff_sequence",
                            models.SmallIntegerField(blank=True, null=True),
                        ),
                        (
                            "order",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="trip_manifests",
                                to="api.order",
                            ),
                        ),
                        (
                            "trip",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="manifests",
                                to="logistics.deliverytrip",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "TRIP_MANIFESTS",
                        "managed": True,
                    },
                ),
                migrations.CreateModel(
                    name="VehicleStatusHistory",
                    fields=[
                        (
                            "history_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "status_changed_to",
                            models.BigIntegerField(blank=True, null=True),
                        ),
                        (
                            "issue_type",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "component_location",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        ("description", models.TextField(blank=True, null=True)),
                        (
                            "photo_url",
                            models.CharField(blank=True, max_length=500, null=True),
                        ),
                        ("start_date", models.DateTimeField(blank=True, null=True)),
                        ("end_date", models.DateTimeField(blank=True, null=True)),
                        (
                            "trip",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="vehicle_status_history",
                                to="logistics.deliverytrip",
                            ),
                        ),
                        (
                            "vehicle",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="status_history",
                                to="logistics.vehicle",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "VEHICLE_STATUS_HISTORY",
                        "managed": True,
                    },
                ),
            ],
        ),
    ]
