# Generated by Django 6.1.1 on 2026-09-30 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_orderitem_calendar_orderitem_order_and_more"),
        ("logistics", "0002_alter_logisticsbusiness_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('"LOGISTICS_BUSINESSES"') IS NOT NULL THEN
                                IF to_regclass('"LOGISTICS_COMPANIES"') IS NOT NULL THEN
                                    RAISE EXCEPTION 'Both LOGISTICS_BUSINESSES and LOGISTICS_COMPANIES exist';
                                END IF;
                                ALTER TABLE "LOGISTICS_BUSINESSES" RENAME TO "LOGISTICS_COMPANIES";
                            ELSIF to_regclass('"LOGISTICS_COMPANIES"') IS NULL THEN
                                RAISE EXCEPTION 'Neither LOGISTICS_BUSINESSES nor LOGISTICS_COMPANIES exists';
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('"LOGISTICS_COMPANIES"') IS NOT NULL THEN
                                IF to_regclass('"LOGISTICS_BUSINESSES"') IS NOT NULL THEN
                                    RAISE EXCEPTION 'Both LOGISTICS_COMPANIES and LOGISTICS_BUSINESSES exist';
                                END IF;
                                ALTER TABLE "LOGISTICS_COMPANIES" RENAME TO "LOGISTICS_BUSINESSES";
                            ELSIF to_regclass('"LOGISTICS_BUSINESSES"') IS NULL THEN
                                RAISE EXCEPTION 'Neither LOGISTICS_COMPANIES nor LOGISTICS_BUSINESSES exists';
                            END IF;
                        END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameModel(
                    old_name="LogisticsBusiness", new_name="LogisticsCompany"
                ),
                migrations.AlterModelOptions(
                    name="logisticscompany",
                    options={
                        "managed": True,
                        "verbose_name": "logistics company",
                        "verbose_name_plural": "logistics companies",
                    },
                ),
                migrations.AlterModelTable(
                    name="logisticscompany", table="LOGISTICS_COMPANIES"
                ),
            ],
        ),
    ]
