# Generated by Django 6.1.1 on 2026-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality_city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='Philippines', max_length=255)),
                ('gps_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ADDRESSES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('target_table', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AUDIT_LOGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.BigIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.SmallIntegerField(blank=True, null=True)),
                ('date_time_created', models.DateTimeField(blank=True, null=True)),
                ('date_time_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BUSINESSES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('available_stock_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('crop_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('harvested_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CROPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar_status', models.BigIntegerField(blank=True, null=True)),
                ('land_preparation_start', models.DateField(blank=True, null=True)),
                ('land_preparation_end', models.DateField(blank=True, null=True)),
                ('planting_start', models.DateField(blank=True, null=True)),
                ('planting_end', models.DateField(blank=True, null=True)),
                ('harvesting_start', models.DateField(blank=True, null=True)),
                ('harvesting_end', models.DateField(blank=True, null=True)),
                ('packing_duration_days', models.SmallIntegerField(blank=True, null=True)),
                ('expected_quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_harvested_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preorder_lead_time_days', models.SmallIntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CROP_CALENDARS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('crop_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('base_shelf_life_days', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CROP_TYPES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_utilization_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_utilization_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('current_delivery_target', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_status', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DELIVERY_TRIPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_title', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.BigIntegerField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_status', models.BigIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_time_deleted', models.DateTimeField(blank=True, null=True)),
                ('date_time_uploaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ELECTRONIC_DOCUMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email_type', models.BigIntegerField(blank=True, null=True)),
                ('is_verified', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EMAIL_ADDRESSES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnumeratedValue',
            fields=[
                ('enum_id', models.AutoField(primary_key=True, serialize=False)),
                ('enumerated_value_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ENUMERATED_VALUES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_size_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FARMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_title', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_type', models.BigIntegerField(blank=True, null=True)),
                ('listing_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MARKETPLACE_LISTINGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.BigIntegerField(blank=True, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_status', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ORDERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_at_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ORDER_ITEMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_changed_to', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ORDER_STATUS_HISTORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_status', models.BigIntegerField(blank=True, null=True)),
                ('is_verified', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PHONE_NUMBERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripManifest',
            fields=[
                ('manifest_id', models.AutoField(primary_key=True, serialize=False)),
                ('dropoff_sequence', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TRIP_MANIFESTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_language', models.BigIntegerField(blank=True, null=True)),
                ('role', models.BigIntegerField(blank=True, null=True)),
                ('onboarding_status', models.BigIntegerField(blank=True, null=True)),
                ('is_verified', models.SmallIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferred_payment_method', models.BigIntegerField(blank=True, null=True)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'USERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_model', models.CharField(blank=True, max_length=255, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('max_weight_capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_volume_capacity_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('body_type', models.BigIntegerField(blank=True, null=True)),
                ('is_air_conditioned', models.SmallIntegerField(blank=True, null=True)),
                ('fuel_consumption_liters_per_100km', models.SmallIntegerField(blank=True, null=True)),
                ('total_distance_meters', models.BigIntegerField(blank=True, null=True)),
                ('current_health_status', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VEHICLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_changed_to', models.BigIntegerField(blank=True, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('component_location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VEHICLE_STATUS_HISTORY',
                'managed': False,
            },
        ),
    ]
