# Generated by Django 6.1.1 on 2026-09-30 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name="business",
                    options={"managed": True},
                ),
            ],
        ),
    ]
