# Generated by Django 6.1.1 on 2026-09-30 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_orderitem_calendar_orderitem_order_and_more"),
        ("businesses", "0002_alter_business_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('"BUSINESSES"') IS NOT NULL THEN
                                IF to_regclass('"BULK_BUYERS"') IS NOT NULL THEN
                                    RAISE EXCEPTION 'Both BUSINESSES and BULK_BUYERS exist';
                                END IF;
                                ALTER TABLE "BUSINESSES" RENAME TO "BULK_BUYERS";
                            ELSIF to_regclass('"BULK_BUYERS"') IS NULL THEN
                                RAISE EXCEPTION 'Neither BUSINESSES nor BULK_BUYERS exists';
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('"BULK_BUYERS"') IS NOT NULL THEN
                                IF to_regclass('"BUSINESSES"') IS NOT NULL THEN
                                    RAISE EXCEPTION 'Both BULK_BUYERS and BUSINESSES exist';
                                END IF;
                                ALTER TABLE "BULK_BUYERS" RENAME TO "BUSINESSES";
                            ELSIF to_regclass('"BUSINESSES"') IS NULL THEN
                                RAISE EXCEPTION 'Neither BULK_BUYERS nor BUSINESSES exists';
                            END IF;
                        END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RenameModel(old_name="Business", new_name="BulkBuyer"),
                migrations.AlterModelOptions(
                    name="bulkbuyer",
                    options={
                        "managed": True,
                        "verbose_name": "bulk buyer",
                        "verbose_name_plural": "bulk buyers",
                    },
                ),
                migrations.AlterModelTable(name="bulkbuyer", table="BULK_BUYERS"),
            ],
        ),
    ]
