# Generated by Django 6.1.1 on 2026-09-30 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_business_delete_vehicle"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Crop",
                ),
                migrations.DeleteModel(
                    name="CropCalendar",
                ),
                migrations.DeleteModel(
                    name="CropType",
                ),
                migrations.RemoveField(
                    model_name="deliverytrip",
                    name="vehicle",
                ),
                migrations.DeleteModel(
                    name="Farm",
                ),
                migrations.DeleteModel(
                    name="MarketplaceListing",
                ),
                migrations.DeleteModel(
                    name="TripManifest",
                ),
                migrations.RemoveField(
                    model_name="vehiclestatushistory",
                    name="vehicle",
                ),
                migrations.AlterModelOptions(
                    name="address",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="auditlog",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="electronicdocument",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="emailaddress",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="enumeratedvalue",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="order",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="orderitem",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="orderstatushistory",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="phonenumber",
                    options={"managed": True},
                ),
                migrations.AlterModelOptions(
                    name="user",
                    options={"managed": True},
                ),
                migrations.DeleteModel(
                    name="DeliveryTrip",
                ),
                migrations.DeleteModel(
                    name="VehicleStatusHistory",
                ),
            ],
        ),
    ]
