# Generated by Django 6.1.1 on 2026-09-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_crop_delete_cropcalendar_delete_croptype_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="auditlog",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.user",
                    ),
                ),
                migrations.AddField(
                    model_name="electronicdocument",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electronic_documents",
                        to="api.user",
                    ),
                ),
                migrations.AddField(
                    model_name="emailaddress",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_addresses",
                        to="api.user",
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="buyer",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
