# Generated by Django 6.1.1 on 2026-09-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auditlog_user_electronicdocument_user_and_more"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="orderitem",
                    name="calendar",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="farmers.cropcalendar",
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="order",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="api.order",
                    ),
                ),
                migrations.AddField(
                    model_name="orderstatushistory",
                    name="order",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_history",
                        to="api.order",
                    ),
                ),
                migrations.AddField(
                    model_name="phonenumber",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_numbers",
                        to="api.user",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="enumeratedvalue",
                    constraint=models.UniqueConstraint(
                        fields=("type", "value"), name="uq_enumerated_value"
                    ),
                ),
            ],
        ),
    ]
