# Generated by Django 6.1.1 on 2026-09-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitem_calendar_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
