# Generated by Django 6.1.1 on 2026-09-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_verification_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
