# Generated by Django 6.1.1 on 2026-09-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0004_auditlog_user_electronicdocument_user_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Crop",
                    fields=[
                        (
                            "crop_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "batch_number",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "available_stock_kg",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "price_per_kg",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "crop_image_url",
                            models.CharField(blank=True, max_length=500, null=True),
                        ),
                        ("harvested_at", models.DateTimeField(blank=True, null=True)),
                        ("expires_at", models.DateTimeField(blank=True, null=True)),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "CROPS",
                        "managed": True,
                    },
                ),
                migrations.CreateModel(
                    name="CropType",
                    fields=[
                        (
                            "crop_type_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "crop_name",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "category",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "base_shelf_life_days",
                            models.SmallIntegerField(blank=True, null=True),
                        ),
                    ],
                    options={
                        "db_table": "CROP_TYPES",
                        "managed": True,
                    },
                ),
                migrations.CreateModel(
                    name="CropCalendar",
                    fields=[
                        (
                            "calendar_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "calendar_status",
                            models.BigIntegerField(blank=True, null=True),
                        ),
                        (
                            "land_preparation_start",
                            models.DateField(blank=True, null=True),
                        ),
                        (
                            "land_preparation_end",
                            models.DateField(blank=True, null=True),
                        ),
                        ("planting_start", models.DateField(blank=True, null=True)),
                        ("planting_end", models.DateField(blank=True, null=True)),
                        ("harvesting_start", models.DateField(blank=True, null=True)),
                        ("harvesting_end", models.DateField(blank=True, null=True)),
                        (
                            "packing_duration_days",
                            models.SmallIntegerField(blank=True, null=True),
                        ),
                        (
                            "expected_quantity_kg",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "actual_harvested_kg",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "preorder_lead_time_days",
                            models.SmallIntegerField(blank=True, null=True),
                        ),
                        ("delivery_date", models.DateField(blank=True, null=True)),
                        (
                            "crop",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="calendars",
                                to="farmers.crop",
                            ),
                        ),
                        (
                            "pickup_address",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="crop_calendars",
                                to="api.address",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "CROP_CALENDARS",
                        "managed": True,
                    },
                ),
                migrations.AddField(
                    model_name="crop",
                    name="crop_type",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crops",
                        to="farmers.croptype",
                    ),
                ),
                migrations.CreateModel(
                    name="Farm",
                    fields=[
                        (
                            "farm_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "farm_size_hectares",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=10, null=True
                            ),
                        ),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "address",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="farms",
                                to="api.address",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="farms",
                                to="api.user",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "FARMS",
                        "managed": True,
                    },
                ),
                migrations.AddField(
                    model_name="crop",
                    name="farm",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crops",
                        to="farmers.farm",
                    ),
                ),
                migrations.CreateModel(
                    name="MarketplaceListing",
                    fields=[
                        (
                            "listing_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "listing_title",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        ("listing_type", models.BigIntegerField(blank=True, null=True)),
                        (
                            "listing_price_per_kg",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        ("is_active", models.SmallIntegerField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "calendar",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="marketplace_listings",
                                to="farmers.cropcalendar",
                            ),
                        ),
                        (
                            "crop",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="marketplace_listings",
                                to="farmers.crop",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "MARKETPLACE_LISTINGS",
                        "managed": True,
                    },
                ),
            ],
        ),
    ]
