# Generated by Django 6.1.1 on 2026-09-30 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_verification_code_expires_at_and_more'),
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCodeRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account verification'), ('recovery', 'Account recovery')], max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('code_issued', 'Code issued'), ('mailed', 'Mailed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending_review', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('code_issued_at', models.DateTimeField(blank=True, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('mailed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_farmer_codes', to=settings.AUTH_USER_MODEL)),
                ('mailed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailed_farmer_codes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_farmer_code_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_code_requests', to='api.user')),
            ],
            options={
                'db_table': 'FARMER_CODE_REQUESTS',
                'ordering': ['requested_at'],
                'managed': True,
            },
        ),
    ]
