# Generated by Django 6.1.1 on 2026-09-30 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_verification_code'),
        ('farmers', '0002_farmercoderequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAdminAuditEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved request'), ('rejected', 'Rejected request'), ('code_issued', 'Code issued'), ('code_mailed', 'Code mailed'), ('manually_verified', 'Manually verified')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_events', to='farmers.farmercoderequest')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_admin_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_admin_events', to='api.user')),
            ],
            options={
                'db_table': 'FARMER_ADMIN_AUDIT_EVENTS',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FarmerRevokedRefreshToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_refresh_tokens', to='api.user')),
            ],
            options={
                'db_table': 'FARMER_REVOKED_REFRESH_TOKENS',
                'managed': True,
            },
        ),
    ]
