# Generated by Django 6.1.1 on 2026-09-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmeradminauditevent_farmerrevokedrefreshtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmercoderequest',
            options={'managed': True, 'ordering': ['requested_at'], 'permissions': [('view_farmer_applications', 'Can view farmer applications and documents'), ('view_farmer_code_requests', 'Can view farmer code requests'), ('review_farmer_code_requests', 'Can approve or reject farmer code requests'), ('issue_farmer_codes', 'Can issue farmer verification or recovery codes'), ('manually_verify_farmer', 'Can manually verify farmer accounts'), ('view_dashboard_reports', 'Can view dashboard reports'), ('view_dashboard_audit_logs', 'Can view dashboard audit logs'), ('manage_dashboard_records', 'Can create and edit dashboard records')]},
        ),
    ]
